### ISSUE TITLE
Question: Why do you put your `main` file within `lib`?

### ISSUE THREAD

**Issue by reggi** [parro-it/npm-exists#1]
Really looking at some insight into why you chose to put your `main` within `lib`. I'm thinking about doing it too.

**Comment by parro-it** [comment]
There are no strng reasons about. Usually is because I don't want have lot of files in 
root folder. 
I use lib from start, so if the project grow to have lot of files, all process are already automated for source files in lib.

**Comment by reggi** [comment]
I totally agree I like it too, looks cleaner.
