### ISSUE TITLE
Publish version 1.0.0 on npm

### ISSUE THREAD

**Issue by simonepri** [parro-it/npm-exists#11]
The last version published is `0.1.0`
![image](https://user-images.githubusercontent.com/3505087/36646334-8979b266-1a76-11e8-889f-2d72e0b54ff6.png)

And is **insanely** slow.
Can you please publish the new version on `npm`?

**Comment by parro-it** [comment]
Sicuro! Mi sono dimenticato a suo tempo mi sa...

**Comment by simonepri** [comment]
Grazie! Fammi sapere quando hai fatto.

**Comment by parro-it** [comment]
> Grazie! Fammi sapere quando hai fatto.

Dovrei riuscire stasera.

**Comment by parro-it** [comment]
Ho appena pubblicato la versione 1.0.1 su npm.

**Comment by parro-it** [comment]
Che forte parlare in Italiano!

**Comment by simonepri** [comment]
Ahah già fa molto strano.
Thanks! 🎊
